version: "3.9"

services:
  rs3questbuddy_editor:
    build:
      context: .
      dockerfile: Dockerfile
    image: rs3questbuddy-editor:latest
    container_name: rs3questbuddy_editor
    restart: unless-stopped
    env_file:
      - server/.env
    networks:
      - app_net

networks:
  app_net:
    external: true
